server:
  port: 8888

spring:
  output:
      ansi:
        enabled: always

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

logging:
  level:
    '[com.example.demo]': DEBUG
  config:
    classpath: logback/logback.xml
    